<?php

/**
 * @file
 * Contains ubc_ckeditor_widgets.module.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function ubc_ckeditor_widgets_page_attachments_alter(array &$page) {

  $config = \Drupal::config('ubc_ckeditor_widgets.settings');
  $fields = [
    'background_colors' => 'backgroundColors',
    'gap_styles' => 'gapStyles',
    'padding_styles' => 'paddingStyles',
    'margin_styles' => 'marginStyles',
    'table_styles' => 'tableStyles',
    'three_column_layout_styles' => 'threeColumnLayoutStyles',
    'two_column_layout_styles' => 'twoColumnLayoutStyles',
    'width_styles' => 'widthStyles',
  ];

  $settings = [];

  foreach ($fields as $field => $label) {
    $key_value_pairs = $config->get($field);
    if ($key_value_pairs) {
      // Parse the newline-separated value|key pairs.
      $pairs = explode("\n", $key_value_pairs);
      foreach ($pairs as $pair) {
        list($value, $key) = explode('|', $pair, 2);
        $settings[$label][] = [
          'label' => trim($key),
          'value' => trim($value),
        ];
      }
    }
  }

  if (!empty($settings)) {
    $page['#attached']['drupalSettings']['ubcCkeditorWidgets'] = $settings;
  }

}
