#!/bin/bash

## Description: Install Drupal and enable the module
## Usage: install
## Example: "ddev install"

vendor/bin/drush site:install --yes
vendor/bin/drush pm:install ubc_ckeditor_widgets --yes
vendor/bin/drush uli
